config/routes.rb
Rails.application.routes.draw do

  resources :reports
  get 'home/index'
  root 'home#index'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :signatures, only: [:new, :create] do
    collection do
      get :sign
    end
  end

  resources :reports, except: [:edit] do
    member do
      get :verify
      get :print
      patch :cancel
      post :approve
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :professor, class_name: "User", foreign_key: "professor_id"
  belongs_to :supervisor, class_name: "User", foreign_key: "supervisor_id", optional: true

  has_one :signature, through: :user
  has_one :supervisor_signature, through: :supervisor, source: :signature
  has_one :professor_signature, through: :professor, source: :signature

  delegate :sign, to: :signature, prefix: :user, allow_nil: true
  delegate :sign, to: :supervisor_signature, prefix: :supervisor, allow_nil: true
  delegate :sign, to: :professor_signature, prefix: :professor, allow_nil: true
  delegate :name, to: :user, prefix: true, allow_nil: true
  delegate :name, to: :professor, prefix: true, allow_nil: true
  delegate :name, to: :supervisor, prefix: true, allow_nil: true

  validates :company, presence: true
  validates :educational_institution, presence: true
  validates :worked_days, presence: true
  validates :daily_worked_hours, presence: true
  validates :performed_activities, presence: true
  validates :supervisor_email, presence: true
  validates :supervisor_nome, presence: true
  validates_format_of :supervisor_email, with: Devise::email_regexp

  attr_accessor :supervisor_email, :supervisor_nome

  def finished?
    return false unless approved
    [user_sign, professor_sign, supervisor_sign].any?
  end

  def professor_approved?
    return false unless approved
    professor_sign.present?
  end

  def rejected?
    return false if approved
    [canceled_at, cancel_reason].any?
  end

  def approve!
    update_column(:approved, true)
  end

  def cancel!
    update_column(:canceled_at, Time.now)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include SignatureTokenConcern

  before_action :set_report, only: [:show, :edit, :update, :destroy, :print, :verify, :cancel, :approve]
  before_action :set_professors, only: [:new, :create]
  before_action :authenticate_user!, except: [:print]

  def index
    reports_collection
  end

  def show
    redirect_to verify_report_path(@report) if current_user.coordenador?

  end

  def new
    @report = Report.new

  end


  def verify
    return render_unauthorized unless current_user.coordenador?
  end

  def approve
    return render_unauthorized unless current_user.coordenador?

    if @report.update_column(:approved, true)
      redirect_to reports_path
      flash[:notice] = "O Relatório foi aprovado!"
    end
  end

  def cancel
    return render_unauthorized unless current_user.coordenador?

    if @report.update_column(:cancel_reason, cancel_report_params['cancel_reason'])
      @report.cancel!
      redirect_to reports_path
      flash[:notice]= "O relatório foi rejeitado"
    else
    end
  end


  def create
    @report = Report.new(report_params)

    @report.user_id = current_user.id
    respond_to do |format|
      if @report.save
        SignatureService.new(@report).send_email
        format.html { redirect_to @report, notice: 'O relatório foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def print
    respond_to do |format|
      format.pdf do
        doc = ReportService.new(@report)
        send_data doc.render, type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_report
      @report = Report.find(params[:id]).decorate
    end

    def report_params
      params.require(:report).permit(:company, :educational_institution, :worked_days, :daily_worked_hours,
                                     :report_date, :performed_activities, :supervisor_email, :supervisor_nome, :professor_id)
    end

    def cancel_report_params
      params.require(:report).permit(:cancel_reason)
    end


    def authenticate_print
      user_signed_in? ? authenticate_user! : validate_token
    end

    def reports_collection
      if current_user.admin?
        @reports = Report.all.decorate

      elsif current_user.coordenador?
        @reports = fetch_reports.order('created_at DESC')
                                .decorate

      else
        @reports = Report.where(user_id: current_user.id).decorate
      end
    end

    def fetch_reports
      case params[:r]

      when 'rejected'
        rejected_reports
      when 'approved'
        approved_reports
      else
        pending_reports
      end
    end

    def pending_reports
      Report.where(professor_id: current_user.id)
            .where('canceled_at IS NULL')
            .where('cancel_reason IS NULL')
            .where(approved: false)
    end

    def rejected_reports
      Report.where(professor_id: current_user.id)
            .where('canceled_at IS NOT NULL')
            .where(approved: false)
    end

    def approved_reports
      Report.where(professor_id: current_user.id)
            .where(approved: true)
    end

    def set_professors
      @professors = User.where(coordenador: true)
    end

end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= current_user.name %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="field">
    <%= form.label :institution %>
    <%= form.text_field :institution %>
  </div>

  <div class="field">
    <%= form.label :report_type %>
    <%= form.text_field :report_type %>
  </div>

  <div class="field">
    <%= form.label :report_date %>
    <%= form.date_select :report_date %>
  </div>

  <div class="field">
    <%= form.label :hours_per_day %>
    <%= form.number_field :hours_per_day %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.text_field :month %>
  </div>

  <div class="field">
    <%= form.label :working_days %>
    <%= form.number_field :working_days %>
  </div>

  <div class="field">
    <%= form.label :activities %>
    <%= form.text_field :activities %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/_form.html.haml
.card.card-outline-secondary.col-10
  %h2.card-title.mt-3.mx-auto Novo Relatório
  .card-body
    = form_for @report, html: { class: 'form' } do |f|
      - if @report.errors.any?
        #error_explanation
          %h4.mx-auto= "#{pluralize(@report.errors.count, "erros")} impediram este relatório de ser salvo:"
          %ul.list-group
            - @report.errors.full_messages.each do |message|
              %li.list-group-item= message
      .row
        .form-group.col-6
          = f.label :educational_institution, class: "col-form-label form-control-label"
          = f.text_field :educational_institution, class: "form-control disabled", value: "Fundação Herminio Ometto - Uniararas", readonly: true

        .form-group.col-6
          = f.label :professor, class: "col-form-label form-control-label"
          = f.select(:professor_id , @professors.collect { |u| [u.name, u.id] }, {:include_blank => "Selecione"}, { class: "form-control" })

      .row
        .form-group.col-4
          = f.label :company, class: "col-form-label form-control-label"
          = f.text_field :company, class: "form-control"

        .form-group.col-4
          = f.label :supervisor_email, class: "col-form-label form-control-label"
          = f.text_field :supervisor_email, class: "form-control"

        .form-group.col-4
          = f.label :supervisor_nome, class: "col-form-label form-control-label"
          = f.text_field :supervisor_nome, class: "form-control"

      .row
        .form-group.col-6
          = f.label :worked_days, class: "mr-5 col-form-label form-control-label"
          = f.select(:worked_days, 0..31, {:include_blank => "-"}, { class: "form-control" })

        .form-group.col-6
          = f.label :daily_worked_hours, class: "mr-5 col-form-label form-control-label"
          = f.select(:daily_worked_hours, 0..6, {:include_blank => "-"}, { class: "form-control" })

      .form-group
        = f.label :performed_activities, class: "row col-form-label form-control-label"
        = f.text_area(:performed_activities, {class: "row form-control"})

      .form-group.row
        = f.label :report_date, class: "mr-2 col-form-label form-control-label"
        = f.text_field(:report_date, {class: "col-3"})
      .row
        .col-12.mr-5
          = f.submit 'Salvar', class: "btn-block btn-primary"

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Company</th>
      <th>Institution</th>
      <th>Type</th>
      <th>Report date</th>
      <th>Hours per day</th>
      <th>Month</th>
      <th>Working days</th>
      <th>Total Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.user_id %></td>
        <td><%= report.company %></td>
        <td><%= report.institution %></td>
        <td><%= report.report_type %></td>
        <td><%= report.report_date %></td>
        <td><%= report.hours_per_day %></td>
        <td><%= report.month %></td>
        <td><%= report.working_days %></td>
        <td><%= report.decorate.worked_hours %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'PDF', export_report_path(report) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>
<div>
  <%= link_to  "Back", root_path %>
</div>

app/views/reports/index.html.haml
.card.mt-5

  %h2.card-title.mx-auto.mt-5 Relatórios

  .card-body
    %table.table
      %thead
        %tr
          - unless current_user.coordenador?
            %th Mês
            %th Empresa
            %th Instituição
            %th Total de Horas
            %th Status
            %th
            %th Ações
            %th
          - if current_user.coordenador?
            %th Aluno
            %th Mês
            %th Dias Trabalhados
            %th Horas Totais
            %th Status
            %th



      %tbody
        - @reports.each do |report|
          %tr
            - unless current_user.coordenador?
              %td= report.month
              %td= report.company
              %td= report.educational_institution
              %td= report.total_hours
            - if current_user.coordenador?
              %td= report.user_name
              %td= report.month
              %td= report.worked_days
              %td= report.total_hours
            %td
              - if report.professor_approved?
                %i.fas.fa-check-circle.fa-lg
              - elsif report.rejected?
                %i.fas.fa-times-circle.fa-lg
              - else
                %i.fas.fa-ellipsis-h.fa-lg

            %td
              - url = current_user.coordenador? ? verify_report_path(report) : report
              = link_to 'Visualizar', url
            - unless current_user.coordenador?
              %td
                = link_to 'Imprimir', print_report_path(report, format: "pdf"), target: "_blank"
              %td
                = link_to 'Excluir', report, method: :delete, data: { confirm: 'Vocë tem certeza?' }

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/new.html.haml
.container
  %br
  = render 'form'

  = link_to 'Back', reports_path

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @report.user.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @report.company %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @report.institution %>
</p>

<p>
  <strong>Type:</strong>
  <%= @report.report_type %>
</p>

<p>
  <strong>Report date:</strong>
  <%= @report.report_date %>
</p>

<p>
  <strong>Hours per day:</strong>
  <%= @report.hours_per_day %>
</p>

<p>
  <strong>Month:</strong>
  <%= @report.month %>
</p>

<p>
  <strong>Working days:</strong>
  <%= @report.working_days %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @report.activities %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/reports/show.html.haml
.row 
  .mt-5.col-6
    %h4.mx-5 Status do Relatório

    .card-body
      %table.table
        %tbody
          %tr
            %th Assinatura do estagiário
            %td
              - if @report.user_sign.present?
                %i.fas.fa-check-circle.fa-lg
              - else
                = link_to('Assinar', "#{new_signature_path}?rid=#{@report.id}")
          %tr
            %th Assinatura do supervisor
            %td
              - if @report.supervisor_sign.present?
                %i.fas.fa-check-circle.fa-lg
              - else
                %i.fas.fa-times-circle.fa-lg
          %tr
            %th Assinatura/Aprovação do coordenador
            %td
              - if @report.professor_approved?
                %i.fas.fa-check-circle.fa-lg
              - elsif @report.rejected?
                %i.fas.fa-times-circle.fa-lg
              - else
                %i.fas.fa-ellipsis-h.fa-lg


  .col-6
    - if @report.professor_approved?
      %i.fas.fa-check-circle.fa-lg(style="font-size:100px; margin: 10rem 10rem;")
        %h4(style="margin-top: 10px;") Aprovado
    - elsif @report.rejected?
      %i.fas.fa-times-circle.fa-lg(style="font-size:100px; margin: 10rem 10rem;")
        %h4(style="margin-top: 10px;") Rejeitado
    - else
      %i.fas.fa-ellipsis-h.fa-lg(style="font-size:100px; margin: 10rem 10rem;")
        %h4(style="margin-top: 10px;") Pendente

- if @report.rejected?
  .row
    %p
      = @report.cancel_reason

app/views/reports/verify.html.haml
.row
  .mt-5.col-6
    %h4.mx-5 Status do Relatório

    .card-body
      %table.table
        %tbody
          %tr
            %th Aluno
            %td
              = @report.user_name
          %tr
            %th Referente ao mês
            %td
              = @report.month
          %tr
            %th Horas trabalhadas por dia
            %td
              = @report.daily_worked_hours
          %tr
            %th Total de horas trabalhadas
            %td
              = @report.total_hours
          %tr
            %th Assinatura do supervisor presente?
            %td
              - if @report.supervisor_sign.present?
                Sim
              - else
                Não
          %tr
            %th Status
            %td
              - if (@report.professor_sign.nil? && !@report.rejected?)
                = link_to('Assine', "#{new_signature_path}?rid=#{@report.id}")
              - elsif (!@report.approved? && !@report.rejected?)
                = link_to 'Aprovar Relatório', approve_report_path(@report), method: :post, class: 'btn btn-success'
              - elsif @report.rejected?
                Rejeitado
              - else
                Aprovado
          - if @report.rejected?
            %tr
              %th Motivo
              %td
                = @report.cancel_reason || ' - '

          %tr
            %th
            %td= link_to 'Visualizar relatório', print_report_path(@report, format: "pdf"), target: "_blank", class: 'btn btn-primary'

- unless @report.rejected? || @report.approved
  .row
    .mt-5.col-12
      .card-body
        = form_for @report, url: cancel_report_path, html: { class: 'form' } do |f|
          .form-group.row
            = f.label :cancel_reason, class: "row col-form-label form-control-label"
            = f.text_area(:cancel_reason, {class: "row form-control"})
          .row
            = f.submit 'Rejeitar', class: "btn btn-danger"